[general]
live_config_reload = true

[font]
size = 10.0

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[window]
opacity = 0.9
padding = { x = 10, y = 10 }
startup_mode = "Maximized"
decorations = "none"
